Repository sanchitc05/Trip-Tailor, pull requests merged in 2025-01, with the labels that each got.

#4 Update README.md
  README.md
Labels: documentation, enhancement, good first issue

#7 Update README.md
  README.md
Labels: documentation, BEGINNER, SWOC

#15 UI Enhancements
  Frontend/Images/travel-home.jpg
  Frontend/styles.css
  index.html
Labels: enhancement, SWOC, INTERMEDIATE

#17 updated changes in contributor page and navbar
  Frontend/styles.css
  contributors/contributor.css
  contributors/contributor.html
  contributors/contributor.js
  index.html
Labels: enhancement, SWOC, INTERMEDIATE

#18 CHATBOT HAS BEEN ADDED
  index.html
Labels: enhancement, SWOC, ADVANCE

#25 Revamp Contributors Page
  contributors/contributor.css
  contributors/contributor.html
  index.html
Labels: enhancement, SWOC, INTERMEDIATE

#26 api added to contact us page
  contact_us_page/contactus.css
  contact_us_page/contactus.html
  index.html
Labels: enhancement, SWOC, INTERMEDIATE

#27 Added menu bar for mobile size
  Frontend/styles.css
  index.html
Labels: good first issue, BEGINNER, SWOC

#39 sign in and sign up form added
  index.html
  signin/sign-in.css
  signin/sign-in.html
  signin/sign-in.js
Labels: enhancement, SWOC, INTERMEDIATE

#48 Improve start planning button
  Frontend/styles.css
Labels: enhancement, BEGINNER, SWOC

#58 Footer Section enhanced
  Frontend/footer.css
  index.html
Labels: enhancement, SWOC, INTERMEDIATE

#59 faqs link on navbar now working
  Frontend/styles.css
  index.html
Labels: bug, BEGINNER, SWOC

#54 solved issue number #42
  Frontend/styles.css
  index.html
Labels: enhancement, BEGINNER, SWOC

#61 add links to navbar of contributor page
  contributors/contributor.html
Labels: bug, BEGINNER, SWOC

#62 Update footer.css
  Frontend/footer.css
Labels: bug, BEGINNER, SWOC

#66 solved start planning button issue
  Frontend/styles.css
Labels: bug, BEGINNER, SWOC

#45 Travel expense calculator
  requirements.txt
  travel_expense_calculator/calculator/Backend/calc.py
  travel_expense_calculator/calculator/Backend/flightfare.py
  travel_expense_calculator/calculator/Backend/fuel.py
  travel_expense_calculator/calculator/Backend/hotels.py
  travel_expense_calculator/calculator/Backend/iata.py
  travel_expense_calculator/calculator/Backend/redbus.py
  travel_expense_calculator/calculator/Backend/tickets.py
  travel_expense_calculator/calculator/Backend/trainno.py
  travel_expense_calculator/calculator/__init__.py
  travel_expense_calculator/calculator/admin.py
  travel_expense_calculator/calculator/apps.py
  travel_expense_calculator/calculator/migrations/__init__.py
  travel_expense_calculator/calculator/models.py
  travel_expense_calculator/calculator/templates/index.html
  travel_expense_calculator/calculator/tests.py
  travel_expense_calculator/calculator/urls.py
  travel_expense_calculator/calculator/views.py
  travel_expense_calculator/manage.py
  travel_expense_calculator/travel_expense_calculator/__init__.py
  travel_expense_calculator/travel_expense_calculator/asgi.py
  travel_expense_calculator/travel_expense_calculator/settings.py
  travel_expense_calculator/travel_expense_calculator/urls.py
  travel_expense_calculator/travel_expense_calculator/wsgi.py
Labels: enhancement, SWOC, ADVANCE

#68 Correct Features link
  index.html
Labels: bug, BEGINNER, SWOC

#71 Update greetings.yml
  .github/workflows/greetings.yml
Labels: bug, SWOC, INTERMEDIATE

#78 Added scroll to top button
  Frontend/styles.css
  index.html
Labels: enhancement, BEGINNER, SWOC

#81 responsiv in mob view of navlinks
  Frontend/styles.css
Labels: bug, BEGINNER, SWOC

#91 enhancing the header section
  Frontend/styles.css
  index.html
  logo.png
Labels: bug, BEGINNER, SWOC

#95 Create Code of Conduct.md
  Code of Conduct.md
Labels: enhancement, BEGINNER, SWOC

#96 navbar added to travel recommendation page
  Trip_Recommendation_Page/Recommendation.css
  Trip_Recommendation_Page/Recommendation.html
  Trip_Recommendation_Page/Recommendation.js
Labels: bug, BEGINNER, SWOC

#85 FOOTER NOT REDIRECT TO ANY PAGE
  index.html
Labels: bug, BEGINNER, SWOC

#100 Update index.html
  index.html
Labels: bug, SWOC, INTERMEDIATE

#102 adding navbar styling in contributors page
  Frontend/styles.css
  contributors/contributor.css
  contributors/contributor.html
  index.html
Labels: bug, SWOC, INTERMEDIATE

#106 added the navbar to the contact us page
  contact_us_page/contactus.html
Labels: bug, BEGINNER, SWOC

#108 footer added to travel recommendation plage
  Trip_Recommendation_Page/Recommendation.html
Labels: bug, BEGINNER, SWOC

#113 ADD TOGGLE BUTTON IN contactus page
  contact_us_page/contactus.css
  contact_us_page/contactus.html
  contact_us_page/contactus.js
Labels: bug, BEGINNER, SWOC

#86 About Us Page
  Frontend/Images/aboutus.jpg
  Frontend/aboutUs/aboutus.css
  Frontend/aboutUs/aboutus.html
Labels: enhancement, SWOC, INTERMEDIATE

#120 Added the navbar to the sign in page
  signin/sign-in.css
  signin/sign-in.html
Labels: bug, BEGINNER, SWOC

#129 navbarlogo-bug-fixed
  Frontend/styles.css
  Trip_Recommendation_Page/Recommendation.css
  contact_us_page/contactus.css
  contributors/contributor.css
  index.html
  signin/sign-in.css
  trip_tailor/frontend/home/static/styles.css
  trip_tailor/staticfiles/styles.css
Labels: bug, SWOC, ADVANCE

#131 added menu bar on the sign in page
  signin/sign-in.css
  signin/sign-in.js
Labels: bug, BEGINNER, SWOC

#135 Fixed Login & Register page UI
  signin/sign-in.css
  signin/sign-in.html
  signin/sign-in.js
Labels: enhancement, SWOC, INTERMEDIATE

#138 footer added to contributors page
  contributors/contributor.css
  contributors/contributor.html
Labels: bug, BEGINNER, SWOC

#145 Added aboutus link on the navbar
  Frontend/aboutUs/aboutus.css
  Frontend/aboutUs/aboutus.html
  Frontend/aboutUs/aboutus.js
  contact_us_page/contactus.html
  contributors/contributor.html
  index.html
  index2.html
  signin/sign-in.html
Labels: bug, SWOC, INTERMEDIATE

#150 Added colored logos
  Frontend/styles.css
  contact_us_page/contactus.css
  contact_us_page/contactus.html
  contributors/contributor.css
  contributors/contributor.html
  index.html
  index2.html
  logo-dark.png
  logo-white.png
  signin/sign-in.css
  signin/sign-in.html
  trip_tailor/frontend/home/static/images/logo-dark.png
  trip_tailor/frontend/home/static/images/logo-white.png
  trip_tailor/frontend/home/templates/index.html
Labels: enhancement, SWOC, INTERMEDIATE

#147 Added footer on the about us page
  Frontend/aboutUs/aboutus.css
  Frontend/aboutUs/aboutus.html
  index2.html
Labels: bug, SWOC, INTERMEDIATE

#158 Added Animations in Footer
  Frontend/footer.css
Labels: enhancement, BEGINNER, SWOC

#163 Create an animated scroll button with progression effect.
  Frontend/styles.css
  index.html
Labels: BEGINNER, SWOC

#159 About us
  Frontend/Images/beach.jpg
  Frontend/Images/culture.jpg
  Frontend/Images/mountain.jpg
  Frontend/aboutUs/aboutus.css
  Frontend/aboutUs/aboutus.html
  index.html
Labels: enhancement, BEGINNER, SWOC

#174 Enhancement Of Contact Us Page
  contact_us_page/contactus.css
  contact_us_page/contactus.html
Labels: bug, SWOC, INTERMEDIATE

#175 solved menu bar issue in index2.html
  index2.html
Labels: bug, BEGINNER, SWOC

#177 made bg of about us page different from navbar FIX #171
  Frontend/aboutUs/aboutus.css
Labels: bug, BEGINNER, SWOC

#172 Improved UI of Travel Recom Page
  contact_us_page/contactus.css
  contact_us_page/contactus.html
Labels: enhancement, SWOC, INTERMEDIATE

#185 New Explore page add in About Section
  Frontend/aboutUs/Explore.html
  Frontend/aboutUs/aboutus.html
Labels: enhancement, SWOC, INTERMEDIATE
